SHELL := /bin/bash

sources = $(shell find -type f -name '*_test.go' -prune \
		  -o -type f -name '*.go' -printf '%P '         \
		  -o -type f -name '*.gotpl' -printf '%P ')
gopath := $(shell echo $$GOPATH)

#===============================================================================
#  release information
#===============================================================================
tool_dir := _tools
release_dir := _release
pkg_dest_dir := $(release_dir)/.pkg

latest_local_devel_branch := $(subst * ,,$(shell git branch --sort='-committerdate' \
	| grep --invert-match master | head --lines=1))
new_tag := $(shell echo "$(latest_local_devel_branch)" | egrep --only-matching '[0-9]+\.[0-9]+\.[0-9]+')

#===============================================================================
#  build options
#===============================================================================
ALL_OS := darwin linux windows
ALL_ARCH := 386 amd64

# Version tag must be annotation tag created by `git tag -a 'x.y.z'`.
version := $(shell git describe --always --dirty 2>/dev/null || echo 'no git tag')
VERSION_PACKAGE := main
build_revision := $(shell git rev-parse --short HEAD)
build_with := $(shell go version)

# static build
static_flags := -a -tags netgo -installsuffix netgo
ld_flags := -s -w -X '$(VERSION_PACKAGE).buildVersion=$(version)' \
	-X '$(VERSION_PACKAGE).buildRevision=$(build_revision)'       \
	-X '$(VERSION_PACKAGE).buildWith=$(build_with)'               \
	-extldflags -static

# go modules (go 1.11)
enable_go_modules_env := GO111MODULE=on

#===============================================================================
#  lint tool
#===============================================================================
GOLINTER := golangci-lint run

#===============================================================================
#  gitignore.io
#===============================================================================
GITIGNORE_BOILERPLATE :=  Vim,Go
gitignore_io_request := https://www.gitignore.io/api/$(GITIGNORE_BOILERPLATE)

#===============================================================================
#  file generation from template engine
#    `mktpl` is used for generating files and .data.yml is used for templating.
#    .data.yml is automatically generated using upper case variables in Makefile.
#===============================================================================
template_dir := $(tool_dir)/etc/template
data_yml := .data.yml
# user-defined function: $(call mktpl,TEMPLATE,OUTPUT)
define mktpl
	@mktpl --data=$(data_yml) --template=$1 >$2
endef

BINARY := $(notdir $(shell go list))
HELP_OUT := $(BINARY) help

#===============================================================================
#  targets
#    `make [help]` shows tasks what you should execute.
#===============================================================================
.DEFAULT_GOAL := help

.PHONY: help ## show help
help:
	@echo 'USAGE: make [target]'
	@echo
	@echo 'TARGETS:'
	@egrep '^.PHONY[^#]+##' $(MAKEFILE_LIST) \
		| sed 's/^.PHONY: //'                \
		| column -t -s '##'

.PHONY: setup ## install devlop tools for this project
setup: $(data_yml)
	go get -v -u github.com/Songmu/gocredits/cmd/gocredits
	go get -v -u github.com/golangci/golangci-lint/cmd/golangci-lint
	go get -v -u github.com/tcnksm/ghr
	go get -v -u github.com/yuta-masano/mktpl

.PHONY: init ## misc tasks for first commit
init: setup .gitignore
	mkdir --parents .github
	${call mktpl,$(template_dir)/ISSUE_TEMPLATE.md,.github/ISSUE_TEMPLATE.md}
	echo -n >CHANGELOG
	git add $(tool_dir) .gitignore .github .golangci.yml CHANGELOG LICENSE Makefile
	git commit --message='First commit'
	cp --archive $(tool_dir)/etc/git_hooks/* .git/hooks/

# You need to do this task when you have updated or installed packages, because godoc
# reads files generated by `go install`.
.PHONY: install ## it is necessary to notify godoc when packages have been updated or installed newly
install:
	$(MAKE) $(gopath)/bin/$(BINARY)

.PHONY: lint ## lint go sources and check whether only LICENSE file has copyright sentence
lint: install
	$(GOLINTER)
	$(tool_dir)/copyright_check.sh

.PHONY: test ## go test
test:
	@$(foreach f, $(shell go list ./... | grep --invert-match /vendor/), $(enable_go_modules_env) go test -v -cover $f;)

.PHONY: push-release-tag ## update CHANGELOG and push all of the your development works
push-release-tag: lint test
	$(tool_dir)/add_changelog.sh "$(new_tag)"
	git checkout master
	git merge --ff "$(latest_local_devel_branch)"
	git push
	$(tool_dir)/add_release_tag.sh "$(new_tag)"
	git branch --move "$(latest_local_devel_branch)" "$(latest_local_devel_branch)-pushed"

.PHONY: clean ## uninstall the binary and remove non versioning files and direcotries
clean:
	$(enable_go_modules_env) go mod tidy
	$(enable_go_modules_env) go clean -i .
	rm --recursive --force $(release_dir)
	rm --force $(data_yml)

.PHONY: doc ## create README.md and DEVELOPMENT.md using template
doc: $(data_yml)
	${call mktpl,$(template_dir)/README.md,README.md}
	${call mktpl,$(template_dir)/DEVELOPMENT.md,DEVELOPMENT.md}
	gocredits . > CREDIT

#---  helper targets  ----------------------------------------------------------

.INTERMEDIATE: $(data_yml)
$(data_yml):
	@$(MAKE) print_mktpl_vars | grep '^[A-Z_]' >$@
	@sed --in-place '/^make\[[0-9]\+\]:.*/d; s/ *$$//' $@

.gitignore:
	curl --location $(gitignore_io_request) >>$@
	echo >>$@
	echo '### my repository' >>$@
	echo '_release' >>$@

$(gopath)/bin/$(BINARY): $(sources)
	$(enable_go_modules_env) CGO_ENABLED=0 go install $(subst -a ,,$(static_flags)) -ldflags "$(ld_flags)"

# Dumping Every Makefile Variable
.PHONY: print_mktpl_vars
print_mktpl_vars:
	$(foreach V,                                         \
		$(sort $(.VARIABLES)),                           \
		$(if                                             \
			$(filter-out environment% default automatic, \
				$(origin $V)),                           \
			$(info $V: $($V))                            \
		)                                                \
	)
