#!/bin/bash

# Fail on unset variables, command errors and pipe fail.
set -o nounset -o errexit -o pipefail

# Prevent commands misbehaving due to locale differences.
export LC_ALL=C LANG=C

SCRIPT_NAME="${0##*/}"

branch_name="$(git symbolic-ref --short HEAD)"

if [ "_$branch_name" == '_master' ]; then
	echo "$SCRIPT_NAME: WARNING: do not commit to the master branch" >&2
	exit 1
fi
