#!/bin/bash

# Fail on unset variables, command errors and pipe fail.
set -o nounset -o errexit -o pipefail

# Prevent commands misbehaving due to locale differences.
export LC_ALL=C LANG=C

branch_name="$(git status -sbu no | cut -b 4-)"
if [ "_$branch_name" == '_master' ]; then
	SCRIPT_NAME="${0##*/}"
	echo "$SCRIPT_NAME: WARNING: do not commit to the master branch" >&2
	exit 1
fi
